package controller;

import model.Clinician;
import model.Patient;
import model.Referral;
import util.FileUtil;

import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayDeque;
import java.util.Deque;

public class ReferralService {

    private static ReferralService instance; // ✅ Singleton
    private final Deque<Referral> referralQueue = new ArrayDeque<>();

    private ReferralService() {}

    public static ReferralService getInstance() {
        if (instance == null) instance = new ReferralService();
        return instance;
    }

    // 管理队列（题目提到 referral queues）
    public void enqueue(Referral r) {
        referralQueue.addLast(r);
    }

    public Referral dequeue() {
        return referralQueue.pollFirst();
    }

    //   email text
    public String generateReferralEmailText(Referral r, Patient p, Clinician referringClinician) {
        String patientName = safe(p == null ? "" : p.getName());
        String clinicianName = safe(referringClinician == null ? "" : referringClinician.getName());
        String clinicianRole = safe(referringClinician == null ? "" : referringClinician.getRole());
        String clinicianSpec = safe(referringClinician == null ? "" : referringClinician.getSpecialty());

        return """
            ==================================================
            NHS e-Referral (Simulated Email - Text Output)
            ==================================================
            To: Secondary Care Team (%s)
            From: %s (%s, %s)
            Subject: Referral %s - %s - Urgency: %s
            Date: %s

            -------------------- Patient ---------------------
            Patient ID: %s
            Name: %s
            NHS Number: %s
            DOB: %s
            Contact: %s / %s
            Registered GP Surgery ID: %s

            ------------------ Referral Info -----------------
            Referral ID: %s
            Referring Clinician ID: %s
            Referred To Clinician ID: %s
            Referring Facility ID: %s
            Referred To Facility ID: %s
            Appointment ID: %s

            Urgency Level: %s
            Reason for Referral:
            %s

            Clinical Summary:
            %s

            Requested Investigations:
            %s

            Notes:
            %s

            -------------------- Status ----------------------
            Status: %s
            Created Date: %s
            Last Updated: %s

            -------------------- Audit -----------------------
            This text file simulates an e-referral email.
            No real email was sent. Record generated by the system.
            """.formatted(
                r.getReferredToFacilityId(),
                clinicianName, clinicianRole, clinicianSpec,
                r.getReferralId(), patientName, r.getUrgencyLevel(),
                r.getReferralDate(),
                r.getPatientId(),
                patientName,
                safe(p == null ? "" : p.getNhsNumber()),
                safe(p == null ? "" : p.getDateOfBirth()),
                safe(p == null ? "" : p.getPhone()),
                safe(p == null ? "" : p.getEmail()),
                safe(p == null ? "" : p.getGpSurgery()),
                r.getReferralId(),
                r.getReferringClinicianId(),
                r.getReferredToClinicianId(),
                r.getReferringFacilityId(),
                r.getReferredToFacilityId(),
                r.getAppointmentId(),
                r.getUrgencyLevel(),
                r.getReferralReason(),
                r.getClinicalSummary(),
                r.getRequestedInvestigations(),
                r.getNotes(),
                r.getStatus(),
                r.getCreatedDate(),
                r.getLastUpdated()
        );
    }


    // writein
    public void saveReferralEmailToFile(Referral r, String emailText) throws IOException {
        String dir = "output/referrals";
        String path = dir + "/" + r.getReferralId() + ".txt";
        FileUtil.writeText(path, emailText);
    }

    // EHR updates
    public void updateEhrAuditTrail(Referral r) throws IOException {
        //
        String dir = "output/audit";
        String path = dir + "/ehr_audit.log";
        String line = LocalDate.now() + " - EHR updated for referral " + r.getReferralId() + " (patient " + r.getPatientId() + ")\n";
        FileUtil.ensureDir(dir);
        java.nio.file.Files.writeString(java.nio.file.Paths.get(path), line,
                java.nio.charset.StandardCharsets.UTF_8,
                java.nio.file.StandardOpenOption.CREATE, java.nio.file.StandardOpenOption.APPEND);
    }

    private String safe(String s) {
        return s == null ? "" : s.trim();
    }
}
